// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/12/2026, 8:15:39 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/mac/Documents/wisekings/admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/admin/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/admin/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/admin/plugins/**/*.{js,ts,mjs}","/Users/mac/Documents/wisekings/admin/composables/**/*.{js,ts,mjs}","/Users/mac/Documents/wisekings/admin/utils/**/*.{js,ts,mjs}","/Users/mac/Documents/wisekings/admin/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/admin/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/admin/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/admin/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;